apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.5
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_DATABASE
      value: mysql
    - name: MYSQL_USER
      value: admin
    - name: MYSQL_ROOT_PASSWORD
      value: admin
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "1000m"