apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
  - name: postgres
    image: postgres:alpine
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_DB
      value: postgres
    - name: POSTGRES_USER
      value: admin
    - name: POSTGRES_PASSWORD
      value: admin
