apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis:alpine
    ports:
    - containerPort: 6379
    resources:
      requests:
        memory: "900Mi"
        cpu: "900m"
      limits:
        memory: "1000Mi"
        cpu: "1000m"
